import { CrawlerInput } from './crawler-input';

/**
 * Input of a Crawler target.
 */
export interface CrawlerTargetInput {
    /**
     * Data defined in the Crawler input that will be sent to the target in page handling request.
     */
    TargetData: CrawlerInput['TargetData']; // from caller input.

    /**
     * Page from the resource.
     */
    Page: unknown[];
}

/**
 * Output of a Crawler target.
 */
export interface CrawlerTargetOutput {
    /**
     * Outputs generated by the page handling.
     */
    Outputs: {
        [FieldID: string]: unknown[] | number;
    };
}
